Fix package name of quickstart example
disneystreaming/smithy4s pull request #1621
Opened 2024-11-11 09:44 UTC by yoohaemin

... so it aligns with the declared namespace

2024-11-11 09:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/disneystreaming/smithy4s?pullRequest=1621) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/disneystreaming/smithy4s?pullRequest=1621) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/disneystreaming/smithy4s?pullRequest=1621) it.</sub>

2024-11-11 10:35 UTC, kubukoz approved these changes

2024-11-11 10:36 UTC, kubukoz requested changes
hmm I was too quick to approve, looks like it's failing. We'll probably have to change it somewhere else too

2024-12-03 09:21 UTC, Baccata commented
Better change the namespace in the smithy code

2025-01-27 16:42 UTC, Baccata commented
Fixed in https://github.com/disneystreaming/smithy4s/pull/1639

2025-01-27 16:42 UTC, closed without merging