[Core] add httpResonseCode support for int enum
disneystreaming/smithy4s pull request #926
Opened 2023-04-24 20:28 UTC by yisraelU

Adds support for in the HttpResponseCodeSchemaVisitor to support targeting an IntEnum with the httpresponseCode trait
closes #916

2023-04-24 20:53 UTC, kubukoz requested changes

2023-04-24 20:53 UTC, kubukoz commented on modules/core/src/smithy4s/http/internals/HttpResponseCodeSchemaVisitor.scala
> +    if (hints.has[smithy.api.HttpResponseCode] && hints.has[IntEnum]) {
**thought:** maybe we don't need the second part of the conditional, as it should already be covered by smithy's own validation?

2023-04-24 20:53 UTC, kubukoz commented on modules/core/src/smithy4s/http/internals/HttpResponseCodeSchemaVisitor.scala
> +  override def enumeration[E](shapeId: ShapeId, hints: Hints, values: List[EnumValue[E]], total: E => EnumValue[E]): ResponseCodeExtractor[E] =
**issue:** this should ideally be covered by a test, even if the implementation is trivial it gives us safety that we won't accidentally break this in the future

2023-04-24 20:54 UTC, kubukoz commented
I'd target 0.17 with this, but arguably it can be considered "behavior changing", so "breaking". The old behavior was wrong, though, so that'd just be a bugfix.

2023-04-24 21:00 UTC, yisraelU commented on modules/core/src/smithy4s/http/internals/HttpResponseCodeSchemaVisitor.scala
> +    if (hints.has[smithy.api.HttpResponseCode] && hints.has[IntEnum]) {
never sure about this type of scenario, like how defensively should I code..
Either way is fine for me

2023-04-25 01:41 UTC, kubukoz commented on modules/core/src/smithy4s/http/internals/HttpResponseCodeSchemaVisitor.scala
> +    if (hints.has[smithy.api.HttpResponseCode] && hints.has[IntEnum]) {
yeah, I'm never sure either :) it's fine to keep it as-is

2023-04-26 15:06 UTC, yisraelU commented on modules/core/src/smithy4s/http/internals/HttpResponseCodeSchemaVisitor.scala
> +  override def enumeration[E](shapeId: ShapeId, hints: Hints, values: List[EnumValue[E]], total: E => EnumValue[E]): ResponseCodeExtractor[E] =
done

2023-04-26 15:56 UTC, kubukoz commented on modules/core/test/src/smithy4s/http/internals/HttpResponseCodeSchemaVisitorSpec.scala
> +    "applying HttpResponseCode works on an enumeration with an intENum hint"
**nitpick:** 
```suggestion
    "applying HttpResponseCode works on an enumeration with an intEnum hint"
```

2023-04-26 15:57 UTC, kubukoz approved these changes

2023-04-26 17:05 UTC, merged