Address #958
disneystreaming/smithy4s pull request #968
Opened 2023-05-17 22:23 UTC by miguel-vila

2023-05-30 14:16 UTC, Baccata commented
Here's what I think we should do : 

1. Introduce a `smithy4s.schema.SchemaType` enumeration (just a good old ADT with only case objects will do)
2. Turn the default method into a `def default[A](id: ShapeId, hints: Hints, schemaType: SchemaType): F[A]`

2023-05-30 14:52 UTC, kubukoz commented
I like that.

2023-06-04 19:38 UTC, Baccata requested changes

2023-06-04 19:38 UTC, Baccata commented on modules/core/src/smithy4s/schema/SchemaVisitor.scala
> +  def lazily[A](shapeId: ShapeId, hints: Hints, suspend: Lazy[Schema[A]]): F[A]
Nope, I'm veto-ing this change (same for nullable). If this change is required for the feature to work, I'll veto the feature.

2023-10-02 09:46 UTC, Baccata commented
Closing this as well as the originating issue : considering the requirement for compiling schemas is `Schema ~> F`, which can take many forms, and considering this feature is not helping the implementation of the OOTB integrations, I don't think it's required at all. 

If you come up with a pattern in userland that you deem really useful, I'm happy to take a look and potentially integrate it, but right now this feels like a "it may come in handy" more than anything.

2023-10-02 09:46 UTC, closed without merging